linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - exportloopref
    - funlen
    - gochecknoinits
    - gocritic
    - goconst
    - gocyclo
    - goimports
    - revive
    - rowserrcheck
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - sqlclosecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

disable:
  - gofumpt
  - errcheck

issues:
  exclude-rules:
    - path: seed.go
      linters:
        - gochecknoinits
        - gosec
    - path: main.go
      linters:
        - unused
    - path: hotel_handler.go
      linters:
        - unused
    - path: user.go
      linters:
        - unused